name: publish_soft_beta_draft

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+sb'

jobs:
  build_release_bundle:
    name: build_release_bundle
    uses: gtgray/shortly/.github/workflows/release_bundle.yml@main

  publish_soft_beta_draft:
    name: publish_soft_beta_draft
    runs-on: ubuntu-latest
    needs: build_release_bundle

    steps:
      - name: publish soft beta draft
        run: ./gradlew publishSoftBetaDraft --stacktrace
