name: publish_soft_beta_draft

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+sb'

jobs:
  publish_soft_beta_draft:
    name: publish_soft_beta_draft
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: create release bundle
        uses: ./.github/actions/release_bundle@main

      - name: publish soft beta draft
        run: ./gradlew publishSoftBetaDraft --stacktrace
