name: release_for_qa

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+qa'

jobs:
  release_qa:
    name: release_qa
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up jdk
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: set up gradlew permissions
        run: chmod +x gradlew

      - name: generate release notes
        shell: bash
        run: |
          export notes=$(git log --no-merges --pretty=%s `git tag --list --sort=-committerdate | head -1`...`git tag --list --sort=-committerdate | head -5 | awk '{split($0, tags, "\n")} END {print tags[1]}'`)
          echo "111$notes111"
          echo "$notes" > ./release_notes.txt
          cat ./release_notes.txt

      - name: make clean
        run: ./gradlew clean --stacktrace

      - name: run lint
        run: ./gradlew lintReleaseQa --stacktrace

      - name: run assemble
        run: ./gradlew assembleReleaseQa --stacktrace

      - name: distribute
        run: ./gradlew appDistributionUploadReleaseQa --stacktrace
