name: verification_on_pull_request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  verification:
    name: verification
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up jdk
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: set up gradlew permissions
        run: chmod +x gradlew

      - name: make clean
        run: ./gradlew clean --stacktrace

      - name: run ktlint
        run: ./gradlew ktlint --stacktrace

      - name: upload ktlint report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: 1. ktlint report
          path: app/build/reports/ktlint/ktlint.xml

      - name: run detekt
        if: success() || failure()
        run: ./gradlew detekt --stacktrace

      - name: upload detekt report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: 2. detekt report
          path: app/build/reports/detekt/detekt-report.html

      - name: run checkstyle
        if: success() || failure()
        run: ./gradlew checkstyle --stacktrace

      - name: upload checkstyle report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: 3. checkstyle report
          path: app/build/reports/checkstyle/checkstyle.html

      - name: run lintDebug
        if: success() || failure()
        run: ./gradlew lintDebug --stacktrace

      - name: upload lint debug report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: 4. lint debug resuts
          path: app/build/reports/lint-results-debug.html

      - name: check unit test coverage
        if: success() || failure()
        run: ./gradlew testDebugUnitTestCoverage --stacktrace

      - name: upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: 5. test report
          path: app/build/test-results/testDebugUnitTest/*.xml

      - name: upload jacoco report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: 6. jacoco report
          path: app/build/reports/jacoco/testDebugUnitTestCoverage/html

  ui_tests:
    name: ui tests
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      # allow tests to continue on other devices if they fail on one device
      fail-fast: true
      matrix:
        # unclear that older versions actually honor command to disable animation.
        # newer versions are reputed to be too slow: https://github.com/ReactiveCircus/android-emulator-runner/issues/222
        api-level:
          - 24
          - 26
          - 29

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up jdk
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: set up gradlew permissions
        run: chmod +x gradlew

      - name: run ui tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          # probably, Galaxy Nexus is the fastest one
          profile: Galaxy Nexus
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew connectedDebugAndroidTest --no-daemon --stacktrace

      - name: upload ui tests report ${{ matrix.api-level }}
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: ui tests report ${{ matrix.api-level }}
          path: ./**/build/reports/androidTests/connected/**