name: Verification on pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up jdk
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: set up gradlew permissions
        run: chmod +x gradlew

      - name: make clean
        run: ./gradlew clean --stacktrace

      - name: run ktlint
        run: ./gradlew ktlint --stacktrace

      - name: run detekt
        if: success() || failure()
        run: ./gradlew detekt --stacktrace

      - name: run checkstyle
        if: success() || failure()
        run: ./gradlew checkstyle --stacktrace

      - name: run lintDebug
        if: success() || failure()
        run: ./gradlew lintDebug --stacktrace

      - name: check unit test coverage
        if: success() || failure()
        run: ./gradlew testDebugUnitTestCoverage --stacktrace
